# Generated by Django 5.2.17 on 2026-08-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.URLField(max_length=512, verbose_name='图片')),
                ('link', models.CharField(blank=True, max_length=256, verbose_name='跳转链接')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MallUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.CharField(max_length=64, unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(blank=True, max_length=64, verbose_name='OpenID')),
                ('nickname', models.CharField(default='微信用户', max_length=64, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, max_length=512, verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '商城用户',
                'verbose_name_plural': '商城用户',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('icon', models.URLField(blank=True, max_length=512, verbose_name='分类图标')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wxcloudrun.category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='收货人')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('province', models.CharField(blank=True, max_length=64, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=64, verbose_name='区/县')),
                ('detail', models.CharField(max_length=256, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='wxcloudrun.malluser', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('status', models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '已完成'), (4, '已取消')], default=0, verbose_name='订单状态')),
                ('total_amount', models.BigIntegerField(default=0, verbose_name='商品总额(分)')),
                ('payment_amount', models.BigIntegerField(default=0, verbose_name='实付金额(分)')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('receiver_name', models.CharField(blank=True, max_length=64, verbose_name='收货人')),
                ('receiver_phone', models.CharField(blank=True, max_length=32, verbose_name='收货电话')),
                ('receiver_address', models.CharField(blank=True, max_length=512, verbose_name='收货地址')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wxcloudrun.malluser', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=256, verbose_name='商品标题')),
                ('subtitle', models.CharField(blank=True, max_length=256, verbose_name='副标题')),
                ('image', models.URLField(max_length=512, verbose_name='主图')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('price', models.BigIntegerField(default=0, verbose_name='售价(分)')),
                ('original_price', models.BigIntegerField(default=0, verbose_name='原价(分)')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='已售数量')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('detail', models.TextField(blank=True, verbose_name='图文详情(HTML)')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='wxcloudrun.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-is_on_sale', 'sort', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods_name', models.CharField(max_length=256, verbose_name='商品名称')),
                ('goods_image', models.URLField(blank=True, max_length=512, verbose_name='商品图片')),
                ('price', models.BigIntegerField(default=0, verbose_name='成交单价(分)')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('item_total', models.BigIntegerField(default=0, verbose_name='小计金额(分)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wxcloudrun.order', verbose_name='所属订单')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxcloudrun.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('is_selected', models.BooleanField(default=True, verbose_name='是否选中')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='wxcloudrun.malluser', verbose_name='所属用户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
