# Generated by Django 4.1.13 on 2026-08-22 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, default='', max_length=256, verbose_name='素材名称')),
                ('file', models.FileField(upload_to='assets/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='图片文件')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材库',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='wxcloudrun.asset', verbose_name='素材库图片'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='wxcloudrun.asset', verbose_name='素材库主图'),
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_products', to='wxcloudrun.asset', verbose_name='素材')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='wxcloudrun.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ['sort', 'id'],
                'unique_together': {('product', 'asset')},
            },
        ),
    ]
