# Generated by Django 4.1.13 on 2026-08-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0002_asset_banner_asset_product_primary_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
    ]
