# Generated by Django 4.1.13 on 2026-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0003_remove_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='express_company',
            field=models.CharField(blank=True, max_length=64, verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='express_company_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='快递公司编码'),
        ),
        migrations.AddField(
            model_name='order',
            name='express_no',
            field=models.CharField(blank=True, max_length=128, verbose_name='快递单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
    ]
