# Generated by Django 4.1.13 on 2026-08-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0004_order_express_company_order_express_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='客户端幂等号'),
        ),
    ]
