# Generated by Django 4.1.13 on 2026-08-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0005_order_client_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.CharField(blank=True, max_length=64, verbose_name='操作人')),
                ('express_company', models.CharField(blank=True, max_length=64, verbose_name='快递公司')),
                ('express_company_code', models.CharField(blank=True, max_length=32, verbose_name='快递公司编码')),
                ('express_no', models.CharField(max_length=128, verbose_name='快递单号')),
            ],
            options={
                'verbose_name': '物流修改记录',
                'verbose_name_plural': '物流修改记录',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='wxcloudrun__user_id_43c7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='wxcloudrun__status_adc6d8_idx'),
        ),
        migrations.AddField(
            model_name='expresslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_logs', to='wxcloudrun.order', verbose_name='订单'),
        ),
    ]
